defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.root_dir}/checkpoints
  filename: "{epoch:03d}"
  monitor: "val/mAP_50"
  mode: "max"
  save_last: True
  every_n_epochs: 1
  save_top_k: 3
  enable_version_counter: False

model_summary:
  max_depth: -1
